// Welcome and Intro
export const HANDLE_SNACKBAR_UPDATE = 'HANDLE_SNACKBAR_UPDATE';
export const CHOOSE_DATABASE = 'CHOOSE_DATABASE';

// Schema App
export const OPEN_TABLE_CREATOR = 'OPEN_TABLE_CREATOR';
export const SAVE_TABLE_DATA_INPUT = 'SAVE_TABLE_DATA_INPUT';
export const DELETE_TABLE = 'DELETE_TABLE';
export const DELETE_FIELD = 'DELETE_FIELD';
export const ADD_FIELD_CLICKED = 'ADD_FIELD_CLICKED';
export const SAVE_FIELD_INPUT = 'SAVE_FIELD_INPUT';
export const HANDLE_FIELDS_UPDATE = 'HANDLE_FIELDS_UPDATE';
export const HANDLE_FIELDS_SELECT = 'HANDLE_FIELDS_SELECT';
export const HANDLE_TABLE_NAME_CHANGE = 'HANDLE_TABLE_NAME_CHANGE';
export const HANDLE_TABLE_ID = 'HANDLE_TABLE_ID';
export const HANDLE_SELECTED_TABLE = 'HANDLE_SELECTED_TABLE';
export const HANDLE_NEW_PROJECT = 'HANDLE_NEW_PROJECT';

// Query App
export const CREATE_QUERY = 'CREATE_QUERY';
export const OPEN_CREATE_QUERY = 'OPEN_CREATE_QUERY';
export const HANDLE_NEW_QUERY_CHANGE = 'HANDLE_NEW_QUERY_CHANGE';
export const CREATE_RETURN_VALUES = 'CREATE_RETURN_VALUES';
export const HANDLE_RETURN_VALUES = 'HANDLE_RETURN_VALUES';
export const HANDLE_SUBQUERY_SELECTOR = 'HANDLE_SUBQUERY_SELECTOR';
export const HANDLE_NEW_QUERY_NAME = 'HANDLE_NEW_QUERY_NAME';
export const HANDLE_NEW_SUBQUERY_TOGGLE = 'HANDLE_NEW_SUBQUERY_TOGGLE';
export const SUBMIT_SUBQUERY_HANDLER = 'SUBMIT_SUBQUERY_HANDLER';
export const DELETED_FIELD_RELATION_UPDATE = 'DELETED_FIELD_RELATION_UPDATE';
