// Welcome and Intro
export const CHOOSE_DATABASE = 'CHOOSE_DATABASE';
export const HANDLE_SNACKBAR_UPDATE = 'HANDLE_SNACKBAR_UPDATE';

// Schema App
export const OPEN_TABLE_CREATOR = 'OPEN_TABLE_CREATOR'
export const SAVE_TABLE_DATA_INPUT = 'SAVE_TABLE_DATA_INPUT';
export const DELETE_TABLE = 'DELETE_TABLE';
export const ADD_FIELD = 'ADD_FIELD';
export const DELETE_FIELD = 'DELETE_FIELD';
export const ADD_FIELD_CLICKED = 'ADD_FIELD_CLICKED';
export const SAVE_FIELD_INPUT = 'SAVE_FIELD_INPUT';
export const HANDLE_FIELDS_UPDATE = 'HANDLE_FIELDS_UPDATE'
export const HANDLE_FIELDS_SELECT = 'HANDLE_FIELDS_SELECT'
export const HANDLE_TABLE_NAME_CHANGE = 'HANDLE_TABLE_NAME_CHANGE'
export const HANDLE_TABLE_ID = 'HANDLE_TABLE_ID'
export const HANDLE_SELECTED_TABLE = 'HANDLE_SELECTED_TABLE'

// Query App
export const CREATE_QUERY = 'CREATE_QUERY'
